version: '3.3'
services:
  database:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: yolo
      POSTGRES_DB: memorygame
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    env_file: .env
    build:
      context: .
    depends_on:
      - database
    ports:
      - '3000:3000'
volumes:
  database-data:
    driver: local
