version: '3.3'
services:
  database:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
  api:
    env_file: .env
    build:
      context: .
    depends_on:
      - database
    ports:
      - '3000:3000'
volumes:
  database-data:
    driver: local
